#CEL: SKLADNIKI
#	KOMENDA

#< - aktualnie przetwarzany plik z listy składników (patrz przykład)
#@ - nazwa pliku docelowego
#^ - składniki

#####ZMIENNE


CXX=g++			#nazwa kompilatora
CXXLAGS=-c 		#opcje kompilatora -c compile and assembly not link
LFLAGS=			#opcje linkera
OBJS=main.o exampleClas.o class2.o


#####LINKOWANIE I KOMPILACJA
prog: $(OBJS)
	$(CXX) $(LFLAGS) $^ -o $@
clean:
	rm -f $(OBJS)

.PHONY: clean
