# Project: stos
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = ../../wyk³ad/programy/wyk1/20-stack5/stack.o ../../wyk³ad/programy/wyk1/20-stack5/teststack.o $(RES)
LINKOBJ  = ../../wyk³ad/programy/wyk1/20-stack5/stack.o ../../wyk³ad/programy/wyk1/20-stack5/teststack.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = stos.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before stos.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "stos.exe" $(LIBS)

../../wyk³ad/programy/wyk1/20-stack5/stack.o: ../../wyk³ad/programy/wyk1/20-stack5/stack.cpp
	$(CPP) -c ../../wyk³ad/programy/wyk1/20-stack5/stack.cpp -o ../../wyk³ad/programy/wyk1/20-stack5/stack.o $(CXXFLAGS)

../../wyk³ad/programy/wyk1/20-stack5/teststack.o: ../../wyk³ad/programy/wyk1/20-stack5/teststack.cpp
	$(CPP) -c ../../wyk³ad/programy/wyk1/20-stack5/teststack.cpp -o ../../wyk³ad/programy/wyk1/20-stack5/teststack.o $(CXXFLAGS)
